### ISSUE TITLE
node execute javascript fail once in a while

### ISSUE THREAD

**Issue by guogeer** [langgenius/dify-sandbox#100]
it is a accidental bug
![screenshot-20241017-135017](https://github.com/user-attachments/assets/0749f9be-fc9a-4413-a75b-65e4b1e009ab)

code:
```javascript
function main({arg1}) {
    return {
        result: JSON.stringify(arg1)
    }
}
```
error:
20.11.1 dbox-459e0614-a459-4bbe-8cf1-70b824f02d4a/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/node_modules/koffi/index.js:562 let lib = load(...args); ^ Error: Failed to load shared library: cannot open shared object file: No such file or directory at module.exports.load (/tmp/sandbox-459e0614-a459-4bbe-8cf1-70b824f02d4a/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/node_modules/koffi/index.js:562:13) at Object.<anonymous> (/tmp/sandbox-459e0614-a459-4bbe-8cf1-70b824f02d4a/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/test.js:4:19) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) at node:internal/main/run_main_module:28:49 Node.js v20.11.1 error: exit status 1

**Comment by chenzikun** [comment]
同样的问题

**Comment by DavideDelbianco** [comment]
+1 Experiencing same issue, especially when running code in iteration node

**Comment by princehaku** [comment]
same problem

**Comment by xiawenbin** [comment]
报错'MODULE_NOT_FOUND'！请问该
怎么解决呢？
equireStack: [ '/tmp/sandbox-9094dcfa-e8ab-4c7e-8908-baa1928b9805/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/test.js' ] } Node.js v20.11.1 box/sandbox-nodejs/nodejs-project/node_temp/node_temp/test.js at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15) at Module._load (node:internal/modules/cjs/loader:985:27) at Module.require (node:internal/modules/cjs/loader:1235:19) at require (node:internal/modules/helpers:176:18) at Object.<anonymous> (/tmp/sandbox-9094dcfa-e8ab-4c7e-8908-baa1928b9805/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/test.js:17:13) at Module._compile (node:internal/modules/cjs/loader:1376:14) at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) at Module.load (node:internal/modules/cjs/loader:1207:32) at Module._load (node:internal/modules/cjs/loader:1023:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) { code: 'MODULE_NOT_FOUND', requireStack: [ '/tmp/sandbox-9094dcfa-e8ab-4c7e-8908-baa1928b9805/var/sandbox/sandbox-nodejs/nodejs-project/node_temp/node_temp/test.js' ] } Node.js v20.11.1 error: exit status 1

**Comment by yinyiyu** [comment]
同样的问题，请问有找到出现问题的原因吗。而且还不是一个必先的问题，而是偶尔回触发
